ACTUAL_CAUSATION_MEASURE: PMI
ASSUME_CUTS_CANNOT_CREATE_NEW_CONCEPTS: false
CACHE_POTENTIAL_PURVIEWS: true
CACHE_REPERTOIRES: true
CES_DISTANCE: SUM_SMALL_PHI
CLEAR_SUBSYSTEM_CACHES_AFTER_COMPUTING_SIA: false
COMPOSITIONAL_STATE_CONFLICTS: GLOBAL
DISTINCTION_PHI_NORMALIZATION: NUM_CONNECTIONS_CUT
DISTINCTION_PHI_UPPER_BOUND_RELATIONS: PURVIEW_SIZE
DISTINCTION_SUM_PHI_UPPER_BOUND: DISTINCT_AND_CONGRUENT_PURVIEWS
HORIZONTAL_PARTITION_CODE: '1210'
IIT_VERSION: 4.0
INTEGRATION_VALUE: MIN
LOG_FILE: pyphi.log
LOG_FILE_LEVEL: INFO
LOG_STDOUT_LEVEL: WARNING
MAXIMUM_CACHE_MEMORY_PERCENTAGE: 50
MIP_TIE_RESOLUTION:
- NORMALIZED_PHI
- NEGATIVE_PHI
NEW_RELATION_SCHEME: UNION_WEIGHTED
NUMBER_OF_CORES: -1
OVERLAP_RATIO: PURVIEW_SIZE
PARALLEL_COMPLEX_EVALUATION: false
PARALLEL_COMPOSITIONAL_STATE_EVALUATION: true
PARALLEL_CONCEPT_EVALUATION: false
PARALLEL_CUT_EVALUATION: false
PARALLEL_MECHANISM_PARTITION_EVALUATION: false
PARALLEL_PURVIEW_EVALUATION: 4.0
PARTITION_TYPE: ALL
PRECISION: 13
PRINT_FRACTIONS: true
PROGRESS_BARS: false
PURVIEW_TIE_RESOLUTION: PHI
RAY_CONFIG: {}
REDIS_CACHE: false
REDIS_CONFIG:
  db: 0
  host: localhost
  port: 6379
  test_db: 1
RELATION_COMPUTATION: CONCRETE
RELATION_ENFORCE_NO_DUPLICATE_PURVIEWS: false
RELATION_PARTITION_AGGREGATION: SUM
RELATION_PARTITION_TYPE: TRI
RELATION_PHI_SCHEME: MINIMAL_OVERLAP_RATIO_TIMES_DISTINCTION_PHI
RELATION_POTENTIAL_PURVIEWS: WHOLE
RELATION_SAMPLE_DEGREES: false
RELATION_SAMPLE_SIZE: 1000
RELATION_SAMPLE_TIMEOUT: 1.0
RELATION_SUM_PHI_UPPER_BOUND: DISTINCT_AND_CONGRUENT_PURVIEWS
REPERTOIRE_DISTANCE: GENERALIZED_INTRINSIC_DIFFERENCE
REPERTOIRE_DISTANCE_INFORMATION: GENERALIZED_INTRINSIC_DIFFERENCE
REPR_VERBOSITY: 2
SINGLE_MICRO_NODES_WITH_SELFLOOPS_HAVE_PHI: false
STATE_TIE_RESOLUTION: PHI
SYSTEM_CUTS: 3.0_STYLE
SYSTEM_PARTITION_INCLUDE_COMPLETE: false
SYSTEM_PARTITION_TYPE: SET_UNI/BI
VALIDATE_CONDITIONAL_INDEPENDENCE: true
VALIDATE_SUBSYSTEM_STATES: true
WELCOME_OFF: false
