ACTUAL_CAUSATION_MEASURE: PMI
ASSUME_CUTS_CANNOT_CREATE_NEW_CONCEPTS: false
CACHE_POTENTIAL_PURVIEWS: true
CACHE_REPERTOIRES: true
CES_DISTANCE: SUM_SMALL_PHI
CLEAR_SUBSYSTEM_CACHES_AFTER_COMPUTING_SIA: false
COMPOSITIONAL_STATE_CONFLICTS: GLOBAL
CONGRUENCE_RATIO: PURVIEW_SIZE
DISTINCTION_PHI_UPPER_BOUND_RELATIONS: PURVIEW_SIZE
DISTINCTION_SUM_PHI_UPPER_BOUND: DISTINCT_AND_CONGRUENT_PURVIEWS
HORIZONTAL_PARTITION_CODE: '1210'
IIT_VERSION: maximal-state-first
LOG_FILE: pyphi.log
LOG_FILE_LEVEL: INFO
LOG_STDOUT_LEVEL: WARNING
MAXIMUM_CACHE_MEMORY_PERCENTAGE: 50
MICE_TIE_RESOLUTION: MAX_INFORMITAVENESS_THEN_SMALLEST_PURVIEW
NUMBER_OF_CORES: -1
OVERLAP_RATIO: PURVIEW_SIZE
PARALLEL_COMPLEX_EVALUATION: true
PARALLEL_COMPOSITIONAL_STATE_EVALUATION: true
PARALLEL_CONCEPT_EVALUATION: true
PARALLEL_CUT_EVALUATION: true
PARTITION_TYPE: ALL
PRECISION: 13
PRINT_FRACTIONS: true
PROGRESS_BARS: true
RAY_CONFIG:
  address: auto
REDIS_CACHE: false
REDIS_CONFIG:
  db: 0
  host: localhost
  port: 6379
  test_db: 1
RELATION_COMPUTATION: ANALYTICAL
RELATION_ENFORCE_NO_DUPLICATE_PURVIEWS: false
RELATION_PARTITION_AGGREGATION: SUM
RELATION_PARTITION_TYPE: BI_CUT_ONE
RELATION_PHI_SCHEME: CONGRUENCE_RATIO_TIMES_INFORMATIVENESS
RELATION_POTENTIAL_PURVIEWS: WHOLE
RELATION_SAMPLE_DEGREES: false
RELATION_SAMPLE_SIZE: 1000
RELATION_SAMPLE_TIMEOUT: 1.0
RELATION_SUM_PHI_UPPER_BOUND: DISTINCT_AND_CONGRUENT_PURVIEWS
REPERTOIRE_DISTANCE: IIT_4.0_SMALL_PHI
REPERTOIRE_DISTANCE_INFORMATION: IIT_4.0_SMALL_PHI_NO_ABSOLUTE_VALUE
REPR_VERBOSITY: 2
SINGLE_MICRO_NODES_WITH_SELFLOOPS_HAVE_PHI: false
SYSTEM_CUTS: 3.0_STYLE
SYSTEM_PARTITION_TYPE: TEMPORAL_DIRECTED_BI
VALIDATE_CONDITIONAL_INDEPENDENCE: true
VALIDATE_SUBSYSTEM_STATES: true
WELCOME_OFF: false
